### ISSUE TITLE
Join() - object is not a function (Futures)

### ISSUE THREAD

**Issue by mikemilano** [cykod/Spriter#4]
I've installed via the instructions, but I am running into this error when I try to run spriter:

```
$ spriter assets/

/Users/abcdefg/Spriter/spriter.js:35
      join = Join();
             ^
TypeError: object is not a function
    at loadImages (/Users/abcdefg/Spriter/spriter.js:35:14)
    at spriter (/Users/abcdefg/Spriter/spriter.js:14:14)
    at Object.<anonymous> (/Users/abcdefg/Spriter/bin/spriter:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by jeronimo** [comment]
I made a pull request - https://github.com/cykod/Spriter/pull/5/files but updating to latest packages solved the issue
